name: py310hl_gaps_pub
channels:
  - conda-forge
dependencies:
  - ase
  - ipython
  - missingno
  - notebook
  - pandas
  - pip
  - python=3.10
  - rdkit
  - scikit-learn
  - seaborn
  - xtb
  - xtb-python
  - pip:
    - -r requirements/prod.txt