[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "hl_gaps_pub"  #  Add a project name! VERY IMPORTANT
version = "0.1.0"   # Add a version.  Important for packaging.
description = "A short description of your project" # and a description
readme = "README.md" # If you have a README.md
requires-python = ">=3.10" # specify python versions
# Add any other project metadata here, like authors, urls, etc.
# Example:
# authors = [
#     {name = "Your Name", email = "your.email@example.com"},
# ]
# dependencies = [ # NO! Dependencies are in environment.yml
# ]


[tool.tox]
envlist = ["py", "flake8", "black", "mypy", "docs"]

[testenv]
description = "Run tests with pytest"
skip_install = true  # We use conda to manage the project itself.
commands = [
    "pytest -vv --doctest-modules --cov=hl_gaps_pub --cov-report term-missing --cov-report xml --cov-report html tests"
]

[testenv:flake8]
skip_install = true
commands = ["flake8 hl_gaps_pub tests"]

[testenv:black]
skip_install = true
commands = ["black --check hl_gaps_pub tests"]

[testenv:mypy]
skip_install = true
commands = ["mypy --config-file pyproject.toml hl_gaps_pub"]

[testenv:docs]
description = "Build the documentation"
skip_install = true
commands = ["sphinx-build -W -b html docs docs/_build/html"]

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3

# https://mypy.readthedocs.io/en/stable/config_file.html
[tool.mypy]
python_version = "3.10" # Changed to 3.10 to match environment.yml
ignore_missing_imports = true
scripts_are_modules = true
warn_unused_configs = true
allow_redefinition = true
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
disallow_untyped_calls = true
# disallow_untyped_decorators = true  # Commented out, as in original
disallow_untyped_defs = true
no_implicit_optional = true
# no_implicit_reexport = true  # Commented out, as in original
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_ignores = true

[tool.pylint.master]  #  Keep this as-is if you're using pylint
ignore-paths = ['docs', 'setup.py']
disable = ['R0801']

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-rs --cov=hl_gaps_pub --cov-report=term --durations=10 --import-mode=importlib" #added importlib
filterwarnings = [
    "ignore:.*imp module.*:DeprecationWarning",
    "ignore:.*_yaml extension module.*:DeprecationWarning"
]

[tool.pytest_env]
XTBPATH = "/home/sat/miniforge3/envs/py310hl_gaps_pub/share/xtb"  #  Keep if needed